mysite/urls.py
from django.urls import path, include
from . import views

app_name = 'mysite'

urlpatterns = [
    path('', views.main_page, name='main_page'),
    path('about/', views.about_me, name='about_me'),
]

mywebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mysite.urls', namespace='mysite'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/models.py
from django.db import models
from django.conf import settings


class About(models.Model):
    user_first_name = models.CharField(max_length=255, default='Samuel')
    user_last_name = models.CharField(max_length=255, default='Sabellano')
    user_description = models.TextField(blank=True, null=True, default="I'm a backend developer and UI/UX designer.")
    user_contact_number = models.CharField(max_length=11, default='0955709557')
    user_address = models.CharField(max_length=255, default='492 South St. DBP Village, Ma-a, Davao City')
    user_email = models.EmailField(max_length=255, default='samsabellanojr@gmail.com')
    user_image = models.ImageField(blank=True, null=True, upload_to='about/images/')
    user_instagram_link = models.URLField(null=True, blank=True, default='https://www.instagram.com/sam.sabellano/')
    user_github_link = models.URLField(null=True, blank=True, default='https://github.com/samsabellano')

    class Meta:
        verbose_name_plural = 'About'

    def __str__(self):
        return f'{self.user_first_name} {self.user_last_name}'


class Comment(models.Model):
    comment_fullname = models.CharField(max_length=250)
    comment_email = models.EmailField(max_length=250)
    comment_description = models.TextField()

    def __str__(self):
        return f'{self.comment_fullname} - {self.comment_email}'

mysite/forms.py
from django import forms
from .models import (Comment)



# class CustomUserCreationForm(UserCreationForm):

#     class Meta:
#         model = CustomUser
#         fields = '__all__'


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['comment_fullname', 'comment_email', 'comment_description']

        widgets = {
            'comment_fullname': forms.TextInput(
                attrs={
                    'class': '_comment_input_fields mb-4',
                    'placeholder': 'Fullname'
                }
            ),
            'comment_email': forms.EmailInput(
                attrs={
                    'class': '_comment_input_fields mb-4',
                    'placeholder': 'Email'
                }
            ),
            'comment_description': forms.Textarea(
                attrs={
                    'class': '_comment_input_fields _custom_textarea mb-4',
                    'placeholder': 'Your message'
                }
            ),

        }

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)

        for input_field in self.fields:
            self.fields[input_field].required = True
            self.fields[input_field].label = ''

mysite/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.models import User
from .forms import CommentForm
from .models import (About)


def main_page(request):
    form = CommentForm()
    about_user = About.objects.first()

    if request.method == 'POST':
        form = CommentForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, 'Thank you for sending a message!')
            return redirect(request.path)

    return render(request, 'mysite/main.html', {
            'form': form,
            'about_user': about_user,
        }
    )


def about_me(request):
    form = CommentForm()
    about_user = About.objects.first()

    if request.method == 'POST':
        form = CommentForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, 'Thank you for sending a message!')
            return redirect(request.path)

    return render(request, 'mysite/about.html', {
            'form': form,
            'about_user': about_user
        }
    )

mysite/templates/mysite/about.html
{% extends 'mysite/main.html' %}
{% block about %}
{% if about_user %}
<h2>About Me</h2>
{% if about_user.user_description %}
<p>{{ about_user.user_description }}</p>
{% else %}
<p><strong style="color: red;">Nothing to show.</strong></p>
{% endif %}
{% endif %}
<a href="{% url 'mysite:main_page' %}" class="_read_more">
    <i class='bx bx-chevron-left'></i>
    Back
</a>
{% endblock about %}

mysite/templates/mysite/main.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load crispy_forms_tags %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'image/user.png' %}" type="image/gif">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>

    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <title>My Website | Samuel C. Sabellano Jr.</title>
</head>

<body>
    <div>
        <nav class="navbar navbar-expand-lg fixed-top navbar-light bg-white">
            <a class="navbar-brand" href="{% url 'mysite:main_page' %}"><span class="_lbl_my">my</span><span
                    class="dot">.</span><span class="_lbl_website"><em>website</em></span></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <i class='bx bx-menu-alt-right'></i>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">

                    {% with request.resolver_match.url_name as url_name %}
                    <li class="nav-item">
                        <a class="nav-link {% if url_name == 'main_page' %}active{% endif %}"
                            href="{% url 'mysite:main_page' %}">
                            <i class='bx bxs-home'></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if url_name == 'about_me' %}active{% endif %}"
                            href="{% url 'mysite:about_me' %}">About Me</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == '/about/#skills' %}active{% endif %}"
                            href="#skills">Skills</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#contact">Contact Me</a>
                    </li>
                    {% endwith %}
                </ul>
            </div>
        </nav>
    </div>
    <div class="_banner w-100" id="aboutme">
        <div class="container">
            <div class="_banner_inner">
                <div class="_banner_content d-flex flex-wrap">
                    <div class="col-lg-8">
                        <div class="_banner_left">
                            {% block about %}
                            {% if about_user %}
                            <div class="_owner_info">
                                <small class="_upper_greet">Hello, my name is</small>
                                <h2 class="_banner_name">{{ about_user.user_first_name }}
                                    {{ about_user.user_last_name }}</h2>
                                <p>I'm a web developer and UI/UX designer.</p>
                            </div>
                            <div class="_social_link d-flex flex-wrap">
                                <div class="pb-3">
                                    <a href="{{ about_user.user_instagram_link }}" class="btn _btn_instagram
                                        {% if not about_user.user_instagram_link %}disabled{% endif %}"
                                        target="_blank">
                                        <i class='bx bxl-instagram-alt rounded-circle'></i>
                                        Instagram
                                    </a>
                                </div>
                                <div class="pb-3">
                                    <a href="{{ about_user.user_github_link }}" class="btn _btn_github float-left
                                        {% if not about_user.user_github_link %}disabled{% endif %}" target="_blank">
                                        <i class='bx bxl-github'></i>
                                        Github
                                    </a>
                                </div>
                            </div>

                            <a href="{% url 'mysite:about_me' %}" class="_read_more">
                                Read more
                                <i class='bx bx-chevron-right'></i>
                            </a>
                            {% endif %}
                            {% endblock about %}

                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="_banner-right">
                            {% if about_user.user_image %}
                            <img src="{{ about_user.user_image.url }}" alt="Profile picture"
                                class="_img rounded-circle">
                            {% else %}
                            <img src="{% static 'image/me.png' %}" alt="Profile picture" class="_img rounded-circle">
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="_skills" id="skills">
        <div class="container">
            <div class="_heading mb-4 text-center">
                <h4>Skills</h4>
            </div>
            <div class="_skills_content">
                <div class="card">
                    <img src="{% static 'image/web-dev.png' %}" class="card-img-top" alt="..." height="190">
                    <div class="card-body">
                        <h3 class="card-title">Web App Development</h3>
                        <div id="carouselExampleInterval" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner">
                                <div class="carousel-item active" data-interval="2000">
                                    <div class="_card_icon_container d-flex flex-wrap mb-4">
                                        <img src="{% static 'image/python.png' %}" alt="">
                                        <img src="{% static 'image/django.png' %}" alt="">
                                        <img src="{% static 'image/postgresql.png' %}" alt="">
                                        <img src="{% static 'image/bootstrap.png' %}" alt="">
                                    </div>
                                </div>
                                <div class="carousel-item" data-interval="2000">
                                    <div class="_card_icon_container d-flex flex-wrap mb-4">
                                        <img src="{% static 'image/css3.png' %}" alt="">
                                        <img src="{% static 'image/html5.png' %}" alt="">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <a href="#" class="btn _btn_view_more_skills shadow-sm">View more</a>
                    </div>
                </div>
                <div class="card">
                    <img src="{% static 'image/web-design.jpg' %}" class="card-img-top" alt="..." height="190">
                    <div class="card-body">
                        <h3 class="card-title">UI/UX Design</h3>
                        <div class="_card_icon_container d-flex flex-wrap mb-4">
                            <img src="{% static 'image/xd.png' %}" alt="">
                            <img src="{% static 'image/figma.png' %}" alt="">
                        </div>
                        <a href="#" class="btn _btn_view_more_skills shadow-sm">View more</a>
                    </div>
                </div>
                <div class="card">
                    <img src="{% static 'image/desktop-app-dev.png' %}" class="card-img-top" alt="..." height="190">
                    <div class="card-body">
                        <h3 class="card-title">Desktop App Development</h3>
                        <div class="_card_icon_container d-flex flex-wrap mb-4">
                            <img src="{% static 'image/vb.png' %}" alt="">
                            <img src="{% static 'image/bunifu.png' %}" alt="">
                            <img src="{% static 'image/mysql.png' %}" alt="">
                            <img src="{% static 'image/guna.png' %}" alt="">
                        </div>
                        <a href="#" class="btn _btn_view_more_skills shadow-sm">View more</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="_contact" id="contact">
        <div class="container">
            <div class="_contact_heading mb-4 text-center">
                <h4 class>Contact Me</h2>
            </div>
            <div class="row _contact_content mt-5">
                <div class="col-md-6 mb-4">
                    <div class="_contact_left">
                        <h5 class="mb-4" style="color: #18a558;">Contact info</h5>

                        {% if about_user %}
                        <div class="_contact_box">
                            <div class="d-flex">
                                <div class="_icon">
                                    <i class='bx bxs-map'></i>
                                </div>
                                <div class="_contact_text">
                                    <h6>Address</h6>
                                    <p>{{ about_user.user_address }}</p>
                                </div>
                            </div>
                        </div>
                        <div class="_contact_box">
                            <div class="d-flex">
                                <div class="_icon">
                                    <i class='bx bxs-phone'></i>
                                </div>
                                <div class="_contact_text">
                                    <h6>Contact #</h6>
                                    <p>{{ about_user.user_contact_number }}</p>
                                </div>
                            </div>
                        </div>
                        <div class="_contact_box">
                            <div class="d-flex">
                                <div class="_icon">
                                    <i class='bx bxs-envelope'></i>
                                </div>
                                <div class="_contact_text">
                                    <h6>Email</h6>
                                    <p>{{ about_user.user_email }}</p>
                                </div>
                            </div>
                        </div>
                        {% else %}
                        <div class="_contact_text">
                            <h6>Contact info is currently unavailable.</h6>
                        </div>
                        {% endif %}

                    </div>
                </div>
                <div class="col-md-6">
                    <div class="_contact_right">
                        <h5 class="mb-4" style="color: #18a558;">Send a message</h5>

                        {% if messages %}
                        {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} mb-3 _alert_message mb-4" role="alert">
                            <i class='bx bx-check'></i>
                            {{ message }}
                        </div>
                        {% endfor %}
                        {% endif %}

                        <div class="_comment_box">
                            <form method="POST">
                                {% csrf_token %}
                                {{ form|crispy }}
                                <button class="btn _btn_send_message" type="submit">
                                    Send
                                    <i class='bx bxs-send'></i>
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous">
    </script>
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>